// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	entity "mf-loan/entity"

	mock "github.com/stretchr/testify/mock"
)

// CustomerUseCase is an autogenerated mock type for the CustomerUseCase type
type CustomerUseCase struct {
	mock.Mock
}

// CreateCustomer provides a mock function with given fields: customer
func (_m *CustomerUseCase) CreateCustomer(customer *entity.DetailCustomer) error {
	ret := _m.Called(customer)

	if len(ret) == 0 {
		panic("no return value specified for CreateCustomer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.DetailCustomer) error); ok {
		r0 = rf(customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCustomerByID provides a mock function with given fields: NIK
func (_m *CustomerUseCase) GetCustomerByID(NIK string) (*entity.DetailCustomer, error) {
	ret := _m.Called(NIK)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerByID")
	}

	var r0 *entity.DetailCustomer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.DetailCustomer, error)); ok {
		return rf(NIK)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.DetailCustomer); ok {
		r0 = rf(NIK)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.DetailCustomer)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(NIK)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCustomerUseCase creates a new instance of CustomerUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerUseCase {
	mock := &CustomerUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
