name: Fintech CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.3

      - name: Install required linux library
        run: sudo apt-get -y install gcc-aarch64-linux-gnu

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: CGO_ENABLED=1 go test mf-loan/delivery/http/tests mf-loan/repository/tests mf-loan/usecase/tests -v
